config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  resources :users
  resources :sessions
  resources :leads
  resources :vendors
  get '/logout', to: 'sessions#destroy'
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lead.rb
class Lead < ApplicationRecord
  #belongs_to :vendor

  validates_presence_of :first_name, :last_name, :phone_number, :disposition, :status, :center_code

  def self.search(search, category)
    if category == "First Name"
      category = 'first_name'
    elsif category == "Last Name"
      category = 'last_name'
    elsif category == "Phone Number"
      category = 'phone_number'
    elsif category == "Disposition"
      category = 'disposition'
    elsif category == "Status"
      category = 'status'
    elsif category == "Center Code"
      category = 'center_code' 
     return where("#{category} = ?", search)  
    end
  
  where("#{category} LIKE ?", "%#{search}%")
  end
end

app/models/user.rb
class User < ApplicationRecord
  
  
  validates_presence_of :first_name, :last_name, :email, :hashed_password
  validates_uniqueness_of :email

  validate :check_password

  def check_password
    if @raw_password.length < 8
      @errors.add(:password, "needs to be 8 characters or more")
    end
  end

  def password
    @password ||= BCrypt::Password.new(hashed_password)
  end

  def password=(new_password)
    @raw_password = new_password
    @password = BCrypt::Password.create(new_password)
    self.hashed_password = @password
  end

  def self.authenticate(email, password)
    user = User.find_by(email: email)
    return user if user && user.password == password
  end
end

app/models/vendor.rb
class Vendor < User
  has_many :leads
  
  validates_presence_of :center_code

  def self.search(search, category)
    if category == "First Name"
      category = 'first_name'
    elsif category == "Last Name"
      category = 'last_name'
    elsif category == "Email"
      category = 'email'
    elsif category == "Center Code"
      category = 'center_code' 
      # if search.is_a? String
      #   return @errors = "please put in valid number"
      # end
     return where("#{category} = ?", search)  
    end
  
  where("#{category} LIKE ?", "%#{search}%")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  def index
    @leads = Lead.all
    
    if params[:search]
      if params[:search] == ""
          return @errors = "Please input a search!"
        end
        if params[:category] == "Center Code"
       return @leads = Lead.search(params[:search].to_i, params[:category]).order("created_at DESC")
      end
        
      @leads = Lead.search(params[:search], params[:category]).order("created_at DESC")
      
    else
      @leads = Lead.all.order('created_at DESC')
    end
  end

  def new
  end

  def create
    @user = Lead.new(lead_params)
    if @user.save
      redirect_to home_index_path
    else
      @errors = @user.errors.full_messages
      render :new
    end
  end

  def edit
    @user = Lead.find_by(id: params[:id])
  end

  def show
    @user = Lead.find_by(id: params[:id])
  end

  def update
    @user = Lead.find_by(id: params[:id])
    
      if @user.update_attributes(lead_params)
        redirect_to root_path
      else
        @errors = @user.errors.full_messages
        render :edit
      end
    #end
  end

  

  private
  def lead_params
    params.require(:lead).permit(:first_name, :last_name, :phone_number, :disposition, :status, :center_code)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end


  def create
    @user = User.authenticate(session_params[:email], session_params[:password])
    if @user
      session[:user_id] = @user.id
      redirect_to home_index_path
    else
      @errors = ["That User does not exist."]
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to home_index_path
  end

  private
  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    @key = user_params[:secret_key]
    @user = User.new(user_params)
if @key == "123456"
    if @user.save
      session[:user_id] = @user.id
      redirect_to home_index_path
    else
      @errors = @user.errors.full_messages
      render :new
    end
    else
      @errors = ["Invalid registration key."]
      render :new
    end
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :admin, :secret_key)
  end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  def index
    @vendors = Vendor.all.select {|user| user.admin == false}
    p params[:search]
    if params[:search]
        if params[:search] == ""
          return @errors = "Please input a search!"
        end
        if params[:category] == "Center Code"
       return @vendors = Vendor.search(params[:search].to_i, params[:category]).order("created_at DESC").select {|user| user.admin == false}
      end
      @vendors = Vendor.search(params[:search], params[:category]).order("created_at DESC").select {|user| user.admin == false}
      
    else
      @vendors = Vendor.all.select {|user| user.admin == false}
    end
  end

  def new
  end

  def create
    @center_code = user_params[:center_code]
    p @center_code
    
    @user = Vendor.new(user_params)
    if @center_code == ""
        @user.errors.add(:center_code, "is needed")
      @errors = @user.errors.full_messages
      render :new
    else
    if @user.save
      redirect_to home_index_path
    else
      @errors = @user.errors.full_messages
      render :new
    end
  end
  end

  def edit
    @user = Vendor.find_by(id: params[:id])
  end

  def show
    @user = Vendor.find_by(id: params[:id])
  end

  def update
    @user = Vendor.find_by(id: params[:id])
    @center_code = @user.center_code
    
    # if @center_code == nil || @center_code == ""
    #     @user.errors.add(:center_code, "is needed")
    #   @errors = @user.errors.full_messages
    #   render :edit
    # else
      if @user.update_attributes(vendor_params)
        redirect_to root_path
      else
        @errors = @user.errors.full_messages
        render :edit
      end
    #end
  end

  

  private
  def vendor_params
    params.require(:vendor).permit(:first_name, :last_name, :email, :password, :admin, :center_code)
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :admin, :center_code)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logged_in?
    !!session[:user_id]
  end

  def current_admin
    @current = User.find_by(id: session[:user_id]) if logged_in?
  end

  def current_vendor
    @current = Vendor.find_by(id: session[:user_id]) if logged_in?
  end

  def set_user(user)
    session[:user_id] = user.id
  end

  def owner?(user_id)
    session[:user_id] == user_id
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lead_helper.rb
module LeadHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/home/index.html.erb
<center style="padding-top: 70px;">
<h1>Welcome to Chris's Meds!</h1>
<% if !logged_in? %>
<p>Login or Sign Up to get started!</p>
<% end %>
<% if logged_in? && current_vendor.admin == false %>
  <h3> Welcome back, <%= current_vendor.first_name %> </h3>
   <%= link_to 'Create New Lead', new_lead_path %></p>
   <%= link_to 'View your own Leads', leads_path %></p>
<% end %>

<% if logged_in? && current_admin.admin == true %>
<h3> Welcome back, <%= current_admin.first_name %> </h3>
   <%= link_to 'Create Vendor', new_vendor_path %></p>
   <%= link_to 'View Vendors', vendors_path %></p>
   <%= link_to 'View all Leads', leads_path %></p>
<% end %>
</center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Salesmedsupply</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
    <!-- <link rel="assets/stylesheets/stylesheet" href="assets/stylesheets/stylesheet.css"> -->
    <script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<nav class="navbar navbar-inverse navbar-fixed-top" >
  <div class="container" >
    <div class="navbar-header" >
  <button type="button"
  class="navbar-toggle collapsed"
  data-toggle="collapse"
  data-target="#navbar"
  aria-expanded="false"
  aria-controls="navbar"
  style="background:blue; width: 15%; height: 60px; margin-top: 3%; margin-right: 10%" 
  >
  <span style="width: 100%;" class="sr-only">Toggle navigation</span>
  <span style="width: 100%;" class="icon-bar"></span>
  <span style="width: 100%;" class="icon-bar"></span>
  <span style="width: 100%;" class="icon-bar"></span>
  <span style="width: 100%;" class="icon-bar"></span>

  </button>
 
  <div id="navbar" class="navbar-collapse collapse pull-md-right" >
  <% if !logged_in? %>
    <ul class="nav navbar-nav">
      <li><%= link_to 'Login', new_session_path %></li>
      <li><%= link_to 'Admin Signup', new_user_path %></li>
      <li><%= link_to 'Home', home_index_path %></li>
    </ul>
      <% else %>
    <ul class="nav navbar-nav">
      <li><%= link_to 'Home', home_index_path %></li>
      <li><%= link_to "Log out", logout_path %></li>
    </ul>
  <% end %>
  </div>
  </div>
  </div>
</nav>
  

  <body>
    <%= yield %>
  </body>
  </html>

app/views/leads/edit.html.erb
<center style="padding-top: 70px;">
<% if logged_in? && current_admin.admin == true %>
<h2>Edit Lead</h2>

<% if @errors %>
   <div class="error_container">
       <p><strong> There is a problem</strong></p>
       <% @errors.each do |error| %>
         <p><%= error %></p>
       <% end %>
   </div>
<% end %>

<%= bootstrap_form_for @user, url: {action: "update"} do |f| %>
  
  <%= f.text_field :first_name, placeholder: @user.first_name %><br>
  
  <%= f.text_field :last_name, placeholder: @user.last_name %><br>
  
  <%= f.text_field :phone_number, placeholder: @user.phone_number %><br>

    <%= f.select(:disposition, [['New Lead'], ['Recording Pending'], ['Bad State'], ['Doctor Approval Pending'], ['Script Received Signed'], ['Dr Denied'], ['Transferred to DR - Success'], ['Transferred to DR - Missing Information'], ['QA Approved'], ['QA Rejected']], prompt: @user.disposition) %><br />
 
    <%= f.select(:status, [['Inactive'], ['Activate'], ['Problem'], ['Reject']], prompt: @user.status) %><br />
  
    <%= f.number_field :center_code, placeholder: @user.center_code %><br />
  <%= f.submit "Edit Lead" %>
<% end %>
<% else %>
<h1> You don't have access to this page! </h1>

<% end %>
</center>

app/views/leads/index.html.erb
<div style="padding-top: 100px;">

<%= form_tag(leads_path, :method => "get", id: "search-form") do %>
<%= select_tag 'category', options_for_select(['First Name','Last Name','Phone Number','Disposition', 'Status', 'Center Code'],'First Name') %>
 
  <%= text_field_tag :search, params[:search], placeholder: "Search Leads" %>
  <%= submit_tag "Search" %><em>** Note: Search is case sensitive. ** </em>
<% end %>
</div>
<div style="padding-top: 70px;">



<% if logged_in? && current_admin.admin == true %>
<h2><%= @errors %></h2>
<h2># of results: <%= @leads.count %></h2>
<table>
  <tr>
  <th>First Name</th>
  <th>Last Name</th>
  <th>Phone Number</th>
  <th>Disposition</th>
  <th>Status</th>
  <th>Center Code</th>
</tr>
<% @leads.each do |lead| %>

   <tr>
   <th><%= lead.first_name %></th>
   <th><%= lead.last_name %></th>
   <th><%= lead.phone_number %></th>
   <th><%= lead.disposition %></th>
   <th><%= lead.status %></th>
   <th><%= lead.center_code %></th>
   <th><%= link_to "edit lead", edit_lead_path(lead.id), class: "btn-success btn-sm" %></th>
   </tr>
  
  
<% end %>
</table>
<% end %>


<% if logged_in? && current_vendor.admin == false %>
<h2><%= @errors %></h2>
<h2># of results: <%= @leads.select{|lead| lead.center_code == current_vendor.center_code}.count %></h2>


  <table>
  <tr>
  <th>First Name</th>
  <th>Last Name</th>
  <th>Phone Number</th>
  <th>Disposition</th>
  <th>Status</th>
  <th>Center Code</th>
</tr>
<% @leads.each do |lead| %>
  <% if current_vendor.center_code == lead.center_code %>
<tr>
   <th><%= lead.first_name %></th>
   <th><%= lead.last_name %></th>
   <th><%= lead.phone_number %></th>
   <th><%= lead.disposition %></th>
   <th><%= lead.status %></th>
   <th><%= lead.center_code %></th>
   </tr>
  
  <% end %>
 
<% end %>
</table>
<% end %>
</div>

app/views/leads/new.html.erb
<center style="padding-top: 70px;">
<% if logged_in? && current_vendor.admin == false %>
<h2>Create Lead. Your center code is: <%= current_vendor.center_code %></h2>
<% if @errors %>
     <div class="error_container">
         <p><strong> There is a problem</strong></p>
         <% @errors.each do |error| %>
           <p><%= error %></p>
         <% end %>
     </div>
  <% end %>
<%= bootstrap_form_for :lead, url: {action: "create"} do |f| %>

    <%= f.text_field :first_name, autofocus: true %><br />

    <%= f.text_field :last_name, autofocus: true %><br />
  
    <%= f.text_field :phone_number, autofocus: true %><br />

    <%= f.hidden_field(:disposition, {value: 'New Lead'}) %><br>

    <%= f.hidden_field(:status, {value: 'Inactive'}) %><br>


    <%= f.number_field :center_code, value: current_vendor.center_code %><br />
  
  <%= f.submit "Create New Lead" %>
<% end %>
<% else %>
<h1> You don't have access to this page! </h1>
<% end %>
</center>

app/views/users/new.html.erb
<center style="padding-top: 70px;"><h2>Admin Sign Up</h2>

<% if @errors %>
   <div class="error_container">
       <p><strong> There is a problem</strong></p>
       <% @errors.each do |error| %>
         <p><%= error %></p>
       <% end %>
   </div>
<% end %>

<%= bootstrap_form_for :user, url: {action: "create"} do |f| %>
  
  <%= f.text_field :first_name, placeholder: "First Name" %><br>
  
  <%= f.text_field :last_name, placeholder: "Last Name" %><br>
  
  <%= f.email_field :email, placeholder: "Email" %><br>

  <%= f.hidden_field(:admin, {value: true}) %><br>
  
  <%= f.password_field :password, placeholder: "Password" %><br>

  <%= f.label :secret_key, "(Ask Admin Manager for Key to Create Admin Account)" %>
  <%= f.password_field :secret_key %><br>
  <%= f.submit "Sign Up" %>
<% end %>
</center>

app/views/vendors/edit.html.erb
<center style="padding-top: 70px;">
<% if logged_in? && current_admin.admin == true %>
<h2>Edit Vendor</h2>

<% if @errors %>
   <div class="error_container">
       <p><strong> There is a problem</strong></p>
       <% @errors.each do |error| %>
         <p><%= error %></p>
       <% end %>
   </div>
<% end %>

<%= bootstrap_form_for @user, url: {action: "update"} do |f| %>
  
  <%= f.text_field :first_name, placeholder: @user.first_name %><br>
  
  <%= f.text_field :last_name, placeholder: @user.last_name %><br>
  
  <%= f.email_field :email, placeholder: @user.email %><br>

  <%= f.hidden_field(:admin, {value: false}) %><br>
  <%= f.hidden_field(:password, {value: @user.password}) %><br>

  <%= f.number_field :center_code, placeholder: @user.center_code %><br>
  <%= f.submit "Edit Vendor" %>
<% end %>
<% else %>
<h1> You don't have access to this page! </h1>
<% end %>
</center>

app/views/vendors/index.html.erb
<div style="padding-top: 100px;">

<%= form_tag(vendors_path, :method => "get", id: "search-form") do %>
<%= select_tag 'category', options_for_select(['First Name','Last Name','Email', 'Center Code'],'First Name') %>
 
  <%= text_field_tag :search, params[:search], placeholder: "Search Vendors" %>
  <%= submit_tag "Search" %><em>** Note: Search is case sensitive. ** </em>
<% end %>
</div>



<div style="padding-top: 70px;">
<% if logged_in? && current_admin.admin == true %>
<h2><%= @errors %></h2>
<h2># of results: <%= @vendors.count %></h2>
<h2>View Vendors! </h2>
<table>
  <tr>
  <th>First Name</th>
  <th>Last Name</th>
  <th>Email</th>
  <th>Center Code</th>
</tr>
<% @vendors.each do |vendor| %>
<tr>
   <th><%= vendor.first_name %></th>
   <th><%= vendor.last_name %></th>
   <th><%= vendor.email %></th>
   <th><%= vendor.center_code %></th>
  <th><%= link_to "edit vendor", edit_vendor_path(vendor.id), class: "btn-success btn-sm" %></th>
  </tr>
  
<% end %>
</table>
<% else %>
<h1> You don't have access to this page! </h1>
<% end %>
</div>

app/views/vendors/new.html.erb
<center style="padding-top: 70px;">
<% if logged_in? && current_admin.admin == true %>
<h2>Create Vendor</h2>

<% if @errors %>
   <div class="error_container">
       <p><strong> There is a problem</strong></p>
       <% @errors.each do |error| %>
         <p><%= error %></p>
       <% end %>
   </div>
<% end %>

<%= bootstrap_form_for :user, url: {action: "create"} do |f| %>
  
  <%= f.text_field :first_name, placeholder: "First Name" %><br>
  
  <%= f.text_field :last_name, placeholder: "Last Name" %><br>
  
  <%= f.email_field :email, placeholder: "Email" %><br>

  <%= f.hidden_field(:admin, {value: false}) %><br>
  
  <%= f.password_field :password, placeholder: "Password" %><br>

  <%= f.number_field :center_code, placeholder: "Center Code" %><br>
  <%= f.submit "Create Vendor" %>
<% end %>
<% else %>
<h1> You don't have access to this page! </h1>

<% end %>
</center>